words = [
    "PYTHON", "JAVA", "JAVASCRIPT", "COMPUTER", "PROGRAMMING", "DEVELOPER", 
    "HANGMAN", "ALGORITHM", "DATASTRUCTURE", "MACHINE", "LEARNING", "AI", 
    "GITHUB", "PYCHARM", "TENSORFLOW", "FLASK", "DJANGO", "VSCODE", "DEBUGGING"
]